export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_INFO = 'FETCH_USER_INFO'
export const ASYNC_START = 'ASYNC_START'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const LOGIN_ERROR = 'LOGIN_ERROR'